import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :weather_app, WeatherAppWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: WeatherApp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :weather_app, Weather.WeatherAPI,
  api_key: System.get_env("OPENWEATHER_API_KEY"),
  base_url: "https://api.openweathermap.org/data/2.5"

config :weather_app, WeatherApp.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
